// src/routes/Countdown.svelte
<script lang="ts">
	export let title: string;
	const calculateDaysLeft = (start: Date) => {
		const distance = start.getTime() - new Date().getTime();
		const days = Math.floor(distance / (1000 * 60 * 60 * 24));
		return days;
	};
	const number = calculateDaysLeft(new Date('2023-05-26'));
</script>

{#if number > 0}
	<div class="module mb-2 min-w-[200px] border-2 border-b-0 border-theme-blue">
		<div
			class="bottomBorder 
        before:border-b-2 before:border-theme-blue 
        after:border-b-2 after:border-theme-blue"
		>
			<div class="borderText text-gray-600">
				<span class="text-lg font-bold">{title}</span>
			</div>
		</div>
		<div class="flex justify-center">
			<span class="text-center text-6xl font-medium">{number || '. . .'}</span>
		</div>
	</div>
{/if}

<style>
	.module {
		position: relative;
		padding: 20px 50px;
		min-width: 10;
	}
	.borderText {
		padding-left: 10px;
		padding-right: 10px;
		margin-bottom: -10px;
		text-align: center;
	}
	.bottomBorder {
		display: flex;
		width: 100%;
		position: absolute;
		bottom: 0;
		left: 0;
	}
	.bottomBorder::before {
		display: block;
		content: '';
		flex: 2 0 0;
	}
	.bottomBorder::after {
		display: block;
		content: '';
		flex: 2 0 0;
	}
</style>

// components/landing/Countdown.tsx
import {makeStyles} from "@material-ui/styles";
import React, {useEffect, useState} from "react";

const useStyles = makeStyles({
    module: {
        position: 'relative',
        padding: '20px 50px',
        borderRight: '1px solid #000',
        borderTop: '1px solid #000',
        borderLeft: '1px solid #000',
        minWidth: 170,
    },
    bottomBorder: {
        display: 'flex',
        flexDirection: 'row',
        width: '100%',
        position: 'absolute',
        bottom: 0,
        left: 0,

        '&::before': {
            display: 'block',
            content: '""',
            flex: '2 0 0',
            borderBottom: '1px solid #000',
        },
        '&::after': {
            display: 'block',
            content: '""',
            flex: '2 0 0',
            borderBottom: '1px solid #000',
        },
    },
    borderText: {
        height: 26,
        color: '#000',
        flex: '0 0 150px',
        marginBottom: '-10px',
        textAlign: 'center',
    },
})

interface Props extends React.HTMLAttributes<HTMLDivElement> {
    title: string
}

const Countdown: React.FC<Props> = ({title, className}) => {
    const classes = useStyles()
    const [days, setDays] = useState<number | null>(null)
    const calculateDaysLeft = () => {
        const start = new Date("2021/05/21 18:00")
        const distance = start.getTime() - new Date().getTime()
        const days = Math.floor(distance / (1000 * 60 * 60 * 24));
        setDays(days)
    }
    useEffect(() => {
        const interval = setInterval(() => {
            calculateDaysLeft()
        }, 10000)
        calculateDaysLeft()
        return () => clearInterval(interval)
    })

    if (days && days < 1) {
        return null
    }
    return (
        <div className={className}>
            <div className={classes.module}>
                <div className={classes.bottomBorder}>
                    <div className={classes.borderText}>
                        <span className="font-bold text-lg">{title}</span>
                    </div>
                </div>
                <div>
                    <span className="font-medium text-center text-6xl">{days || ". . ."}</span>
                </div>
            </div>
        </div>
    )
}

export default Countdown
